name: Testing github workflows

on: push

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Étape 1 - Initialisation 
        run: echo "Initialisation..." 
      - name: Étape 2 - Récupération du code 
        uses: actions/checkout@v4 
      - name: Étape 3 - Build 
        run: ubuntu-latest
      - name: Étape 4 - Tests 
        run: mvn test 
      - name: Étape 5 - Packaging 
        run: mvn package 
      - name: Étape 6 - Fin du pipeline 
        run: echo "Pipeline terminé"